// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxdtlpqmwonaeovvqbtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4ZHRscHFtd29uYWVvdnZxYnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTcxNjYsImV4cCI6MjA3MDI5MzE2Nn0.yp_CymPcVfysWUV4Mr8CZMPi_AR0ye_IiAdilPprsgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});